apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  # Select all nodes as BGP speakers for simplicity.
  # For production, you may want to limit this to a subset of nodes.
  nodeSelector: {}
  bgpInstances:
    - name: "my-bgp-instance"
      # Replace with your cluster's local ASN.
      localASN: 64512
      peers:
        - name: "primary-router"
          # Replace with your on-premises router's ASN.
          peerASN: 65550
          # Replace with your router's IP address.
          peerAddress: "192.168.3.1/32"
          peerConfigRef:
            name: "cilium-bgp-peer-config"