apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-config
spec:
  # This resource only holds general session parameters (timers, families, auth)
  families:
    - afi: ipv4
      safi: unicast