apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-config
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
    - name: default
      localASN: 65555
      peers:
        - name: "gateway-peer"
          peerAddress: 192.168.3.1
          peerASN: 65000
          # Reference the common peer configuration defined in Step 3
          peerConfigRef:
            name: cilium-peer-config