apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisement-lb
  labels:
    bgp.cilium.io/advertise: "true"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
  selector:
    matchExpressions:
      - key: type
        operator: NotIn
        values:
          - never-matches