#ENC[AES256_GCM,data:gXQrjCOgXJMpGsypgKAqLbx6dr/vugx6XrkEnSGtJJvz5P0P1u80zBROB2zRBi5J/LUdxGw=,iv:6ypWFFRBlJGlnQwlIa5wi7C/5ccRSC97X/9HoZU9zA4=,tag:40qcoiFGOn7ABNwlv2g05g==,type:comment]
apiVersion: ENC[AES256_GCM,data:bHw=,iv:VnGq/yJsCO22GVsv6aHZxgdf1s3KwafnZE4lBmZzx+Y=,tag:blqjw1670TSx+xFTtEAzLg==,type:str]
kind: ENC[AES256_GCM,data:adxB686o,iv:312u5psslitl4NAIjlNc57by+40M9rrvhiw2To40rTo=,tag:DFWz9TMUCMv8Lq1nV6EStw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o7p4GkfFN24Gk0nmdc8fnYnPdL4mrCeg,iv:tRBgscJA7TWa81bUXLP/i3u7+r45H8g64gGmfVKi/4M=,tag:KMBLaIOQAyCnYol/MVFcjA==,type:str]
    namespace: ENC[AES256_GCM,data:V07lAICADrl6NoQl,iv:FyJjl0akovqZW0NqM63E7ksi5EkhdHyI7LTcILKR0rk=,tag:b/k68UNJhFAjQbHrTuKSRg==,type:str]
type: ENC[AES256_GCM,data:RViTkvxa,iv:igfEnO1AYssJAnk3ENFwFOm9KGnTAV9F9Ct9bcuLO0A=,tag:FrVNYQXTkSj2bZWUjYaU4A==,type:str]
stringData:
    tsig-secret: ENC[AES256_GCM,data:SlrKE+AhzJaljx4VGvxVMjjENfLbuSpyrzIuboGb/wi9SVx6IhckwiFBySc=,iv:V7i6XbnDcd+1Vzp7ed3/BLK84H5my+uFLLjtL6IfXpc=,tag:WO0XnVpMrD3k3D/EbxafAQ==,type:str]
sops:
    age:
        - recipient: age1yr0vav4a94z6jn3u7qcnwjn8jtnw5hegjg9h766hz3e29u32ug3sttvf6v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTzRTbDNpd1I2bFRyTC82
            N0wvUENiZDJnME1HcUlueHR1bWxTV2Mra0VNCkQyckRydWRSMnNnclNiRVpZSExu
            b2FiYkpTUitlT3VSR2ZTMmRSWXBINjgKLS0tIFh3T3NNb3F5Q2dSWFNnS0ljNFYz
            K2VVQzU0SldncXI5RUhTT0pXa2pPdkEKxgycBn7lX2Jyp2BBG0ApFh85UA6roOTR
            atdckSE6E/pdFjIumx66B8+EnM8TFf04fI+RM7FbYaWbOJGInYiQiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T20:00:57Z"
    mac: ENC[AES256_GCM,data:PEE+rpGbtneFcGehuOT/a00T7usMdC5EZQbKif2fDoYfz8NJqLKqCAEHhXvdcomHjVIfs43WKBmegQEvoE9ZJ8dUHxpFILC6lT04M9Uz1wje8xUkRAb/nPFsD7rLe+vJVVhP/J1eo39FDj9MAMsrobLCFHChA00P/SJ51FTcvPQ=,iv:wbAh/gUdg78omuTqDW9nanqZ00oNJDgfUPNibKGYtUU=,tag:GybbJJvqEGmb2lvmaVFzsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
