apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: cert-manager
  interval: 10m # How often to reconcile the release

  install:
    remediation:
      retries: 3
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  values:
    crds:
      enabled: true