apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m # How often to reconcile the release

  install:
    remediation:
      retries: 3
    crds: CreateReplace

  upgrade:
    crds: CreateReplace


  chart:
    spec:
      chart: cert-manager
      version: '>=1.19.2'
      sourceRef:
        kind: OCIRepository
        name: cert-manager-repo
        namespace: cert-manager
      interval: 12h
