apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui-ingress
  namespace: kube-system # Assuming Hubble UI is in kube-system
spec:
  ingressClassName: cilium
  rules:
    - host: hubble.forthebrew.com # Replace with your desired hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hubble-ui # Name of the Hubble UI service
                port:
                  number: 8081 # Port of the Hubble UI service