apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  releaseName: kube-prometheus-stack
  interval: 5m # How often to reconcile the release
  timeout: 5m0s
  prune: true
  dependsOn:
  - name: monitoring

  # Ensure the Helm Controller manages and updates Custom Resource Definitions (CRDs).
  # This is a key feature of Flux's Helm integration.
  install:
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring

  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
      valuesKey: values.yaml