apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 5m # How often to reconcile the release
  timeout: 5m0s

  # Ensure the Helm Controller manages and updates Custom Resource Definitions (CRDs).
  # This is a key feature of Flux's Helm integration.
  install:
    remediation:
        retries: 3
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  chart:
    spec:
      chart: kube-prometheus-stack
      version: '79.9.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h

  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - grafana.forthebrew.com
        path: /
        pathType: Prefix
        annotations:
          # Explicitly request dedicated mode if not set globally
          ingress.cilium.io/loadbalancer-mode: "dedicated"
          # Propagate labels to the hidden LoadBalancer service for IPAM
          service.cilium.io/labels: "io.cilium/lb-ipam-pool=lb-pool-128"
    prometheus:
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - prometheus.forthebrew.com
        paths:
          - /
        pathType: Prefix
        annotations:
          ingress.cilium.io/loadbalancer-mode: "dedicated"
          service.cilium.io/labels: "io.cilium/lb-ipam-pool=lb-pool-128"
      prometheusSpec:
        retention: "45d"

  driftDetection:
    mode: warn
