apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    environment: local
  annotations:
    description: "Namespace for prometheus monitoring system pods"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring2
  labels:
    environment: local
  annotations:
    description: "Test namespace"